atlas/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from revproxy.views import ProxyView

admin.site.site_header = 'Atlas beheer'
admin.site.site_title = 'Atlas beheer'
admin.site.site_url = '/atlas/'

urlpatterns = [
    path('atlas/admin1/', admin.site.urls),
]

if settings.AUTHENTICATION_ENABLE_CREDENTIALS:
    urlpatterns += [
        path('atlas/accounts/', include('django.contrib.auth.urls'))
    ]

if settings.AUTHENTICATION_ENABLE_OIDC:
    urlpatterns += [
        path('atlas/oidc/', include('mozilla_django_oidc.urls'))
    ]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^atlas/media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

    urlpatterns += [
        re_path(r'^api/(?P<path>.*)$', ProxyView.as_view(
            upstream='http://localhost:8050/api/'
        )),
    ]

    urlpatterns += [
        re_path(r'^geoserver/(?P<path>.*)$', ProxyView.as_view(
            upstream='http://localhost:8080/geoserver/'
        )),
    ]

urlpatterns += [
    path('atlas/', include('homepage.urls'), name='homepage'),
    path('tables/', include('tables.urls'), name='tables'),
    path('', include('portal.urls'), name='portal')
]

homepage/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include
from homepage import views, viewclasses
from webservice import views as webservice_views, urls

app_name = 'homepage'

urlpatterns = [
    path('disclaimer', views.v3_disclaimer, name='v3_disclaimer'),
    path('login', viewclasses.LoginView.as_view(
        template_name='v3/login.html'), name='v3_login'),
    path('login/failure', views.v3_login_failure, name='v3_login_failure'),
    path('logout', auth_views.LogoutView.as_view(
        template_name='v3/logout.html'), name='v3_logout'),
    path('admin/', views.v3_admin, name='v3_admin'),
    path('api/v1/token', webservice_views.v3_token, name='v3_token'),
    path('api/v1/', include(urls.api_router.urls)),
    path('convert/<str:output_format>',
         webservice_views.v3_convert, name='v3_convert'),
    re_path('embed', views.embed, name='embed'),
    re_path(r'maps\/((?P<slug>[a-z0-9\-]+)?)', views.v3_map, name='v3_map'),
    re_path(r'((?P<theme_slug>[a-z0-9\-]+)?)', views.v3, name='v3'),
]

homepage/views.py
import logging
import os

from constance.admin import get_values
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseNotFound
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views.decorators.clickjacking import xframe_options_exempt, xframe_options_sameorigin
from django.views.decorators.csrf import ensure_csrf_cookie

from homepage.templatetags.app_version import app_version
from webservice.models import Layer, Map, Viewer

logger = logging.getLogger(__name__)


@xframe_options_exempt
def embed(request):
    authorized_layers = Layer.authorized.for_request(request)
    visible_layers = authorized_layers.filter(~Q(not_in_atlas=True))

    context = {
        'data': {
            'is_embed': True,
            'config': _get_config(request),
            'user': _get_user(request),
            'layers': _default_layers() + [layer.to_dict() for layer in visible_layers]
        }
    }

    return render(request, 'v3/app.html', context)


@xframe_options_exempt
@ensure_csrf_cookie
def v3(request, theme_slug=''):
    authorized_layers = Layer.authorized.for_request(request).prefetch_related(
        'layer_source', 'layer_type', 'linked_data', 'templates'
    )

    context = {}

    if theme_slug:
        theme = get_object_or_404(Map, slug=theme_slug)
        visible_layers = authorized_layers.filter(map=theme)
        context['title'] = theme.title
    else:
        visible_layers = authorized_layers.filter(~Q(not_in_atlas=True))

    context['data'] = {
        'is_embed': False,
        'config': _get_config(request),
        'user': _get_user(request),
        'layers': _default_layers() + [layer.to_dict() for layer in visible_layers]
    }

    return render(request, 'v3/app.html', context)


def v3_disclaimer(request):
    config = get_values()

    if config.get('DISCLAIMER'):
        return render(request, 'v3/disclaimer.html', {
            'title': 'Disclaimer',
            'content': config.get('DISCLAIMER'),
        })

    return HttpResponseNotFound('Er is geen disclaimer aanwezig')


def v3_login(request):
    return render(request, 'v3/login.html', {
        'title': 'Login'
    })


def v3_login_failure(request):
    return render(request, 'v3/login_failure.html', {
        'title': 'Login mislukt'
    })


@login_required(login_url='admin:login')
@ensure_csrf_cookie
@xframe_options_sameorigin
def v3_admin(request):
    if not request.user.is_superuser:
        return redirect(reverse('admin:login'))

    visible_layers = Layer.authorized.for_request(request).prefetch_related(
        'layer_source', 'layer_type', 'linked_data', 'templates'
    )

    config = _get_config(request)
    config = {
        **config,
        'application_version': app_version(),
        'application_environment': os.getenv('ENVIRONMENT'),
    }

    context = {
        'data': {
            'config': config,
            'user': _get_user(request),
            'layers': _default_layers() + [layer.to_dict() for layer in visible_layers]
        }
    }

    return render(request, 'v3/admin.html', context)


@xframe_options_exempt
def v3_map(request, slug):
    visible_layers = Layer.authorized.for_request(request).prefetch_related(
        'layer_source', 'layer_type', 'linked_data', 'templates'
    )
    visible_map = get_object_or_404(
        Map.authorized.for_request(request), slug=slug)

    context = {
        'data': {
            'config': _get_config(request),
            'user': _get_user(request),
            'map': visible_map.to_dict(),
            'layers': _default_layers() + [layer.to_dict() for layer in visible_layers]
        }
    }

    return render(request, 'v3/map.html', context)


def _default_layers():
    if Layer.objects.filter(is_base=True).count() > 0:
        # Do not return default base layers when the database contains base layers
        return []

    # TODO: Remove default hardcoded layers
    return [
        {
            'id': 'brt_topo_kaart_totaal',
            'title': 'Kaart grijs',
            'name': 'topp:topografische_kaart_grijs',
            'opacity': 0.9,
            'url': 'https://datalab.purmerend.nl/geoserver/topp/wms',
            'server_type': 'geoserver',
            'is_base': True,
            'is_visible': True,
            'metadata': {
                'description': 'Topografische achtergrondkaart',
                'organization': 'Gemeente Purmerend',
                'updated': '2020'
            }
        },
        {
            'id': 'purm_lufo2020',
            'title': 'Luchtfoto 2020',
            'name': 'topp:Lufo_Totaal_2020',
            'opacity': 0.9,
            'url': 'https://datalab.purmerend.nl/geoserver/topp/wms',
            'server_type': 'geoserver',
            'is_base': True,
            'is_visible': False,
            'metadata': {
                'description': 'Luchtfoto',
                'organization': 'Gemeente Purmerend',
                'updated': '2020'
            }
        },
    ]


def _get_config(request):
    config = get_values()

    return {
        'organization_name': config.get('ORGANIZATION_NAME'),
        'organization_logo': settings.MEDIA_URL + config.get('ORGANIZATION_LOGO') if config.get(
            'ORGANIZATION_LOGO') else None,
        'organization_image': settings.MEDIA_URL + config.get('ORGANIZATION_IMAGE') if config.get(
            'ORGANIZATION_IMAGE') else None,
        'organization_primary_color': config.get('ORGANIZATION_PRIMARY_COLOR'),
        'organization_introduction': config.get('ORGANIZATION_INTRODUCTION'),
        'organization_header': config.get('ORGANIZATION_HEADER'),
        'position': {
            'zoom': config.get('POSITION_ZOOM'),
            'center': {
                'x': config.get('POSITION_CENTER_X'),
                'y': config.get('POSITION_CENTER_Y')
            }
        },
        'map_area': config.get('MAP_AREA'),
        'suggest_municipalities': config.get('SUGGEST_MUNICIPALITIES'),
        'show_disclaimer': config.get('DISCLAIMER') != '',
        'features': {
            'print': config.get('FEATURE_PRINT'),
            'draw': config.get('FEATURE_DRAW'),
            'portal': config.get('FEATURE_PORTAL'),
            'filterable_legend': config.get('FEATURE_FILTERABLE_LEGEND')
        },
        'viewers': [viewer.to_dict() for viewer in Viewer.visible.for_request(request)],
    }


def _get_user(request):
    user = request.user

    if not user.is_authenticated:
        return None

    return {
        'id': user.id,
        'username': user.username,
        'name': user.name,
    }

homepage/templates/v3/_base.html
{% load django_vite %}
{% load static %}
<!DOCTYPE html>
<html lang="nl">
  <head>
    <title>{% if title %}{{ title }} · {% endif %}Atlas · {{ config.ORGANIZATION_NAME }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" >
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
    <link rel="shortcut icon" href="{% if config.FAVICON_URL %}{{ config.FAVICON_URL }}{% else %}{% static 'img/favicon.ico' %}{% endif %}" />
    {% vite_hmr_client %}
    {% vite_asset 'src/app.js' %}
</head>
  <body>
    {% block content %}{% endblock %}

    {% if google_maps %}
      <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ google_maps.api_key }}"></script>
    {% endif %}

    {% if street_smart %}
      <script type="text/javascript" src="https://unpkg.com/react@18.2.0/umd/react.production.min.js"></script>
      <script type="text/javascript" src="https://unpkg.com/react-dom@18.2.0/umd/react-dom.production.min.js"></script>
      <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@main/dist/en/v6.12.0/build/ol.js"></script>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"></script>
      <script type="text/javascript" src="https://streetsmart.cyclomedia.com/api/v23.7/StreetSmartApi.js"></script>
    {% endif %}


    {% if config.MATOMO_URL %}
      <script type="text/javascript">
          var _paq = window._paq || [];
          _paq.push(['trackPageView']);
          _paq.push(['enableLinkTracking']);
          (function() {
              var u="{{ config.MATOMO_URL }}/";
              _paq.push(['setTrackerUrl', u+'matomo.php']);
              _paq.push(['setSiteId', {{ config.MATOMO_SITE_ID }}]);
              var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
              g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
          })();
      </script>
    {% endif %}
  </body>
</html>

homepage/templates/v3/admin.html
{% load django_vite %}
{% load static %}
<!DOCTYPE html>
<html lang="nl">
  <head>
    <title>Atlas · {{ config.ORGANIZATION_NAME }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" >

    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
    <link rel="shortcut icon" href="{% if config.FAVICON_URL %}{{ config.FAVICON_URL }}{% else %}{% static 'img/favicon.ico' %}{% endif %}" />

    {% vite_hmr_client %}
    {% vite_asset 'src/admin.js' %}
</head>
  <body>
    <div id="app" class="app"></div>
    {{ data|json_script:"app-data" }}
  </body>
</html>

homepage/templates/v3/app.html
{% extends 'v3/_base.html' %}

{% block content %}
  <div id="app" class="app"></div>
  {{ data|json_script:"app-data" }}
{% endblock %}

homepage/templates/v3/disclaimer.html
{% extends 'v3/_base.html' %}
{% load markdownify %}

{% block content %}
    <div class="content__container">
        <h1>Disclaimer</h1>
        {{ content|linebreaks }}
    </div>
{% endblock %}

homepage/templates/v3/help.html
{% extends 'v3/_base.html' %}
{% load markdownify %}

{% block content %}
    <div class="content__container">
        <h1>Help</h1>
        {{ content | markdown | safe }}
    </div>
{% endblock %}

homepage/templates/v3/login.html
{% extends 'v3/_base.html' %}

{% block content %}
  <div class="login__container">
    {% if AUTHENTICATION_ENABLE_CREDENTIALS %}
      <div class="credentials__container">
        <form method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ next }}">

          <div>
            <div class="login__form-item">
              <label for="id_username">
                Gebruikersnaam
              </label>
              {{ form.username }}
            </div>
            {% for error in form.username.errors %}
                <p>{{ error }}</p>
            {% endfor %}
          </div>

          <div>
            <div class="login__form-item">
              <label for="id_password">
                Wachtwoord
              </label>
              {{ form.password }}
            </div>
            {% for error in form.password.errors %}
                <p>{{ error }}</p>
            {% endfor %}
          </div>

          {{ form.non_field_errors }}

          {% for hidden_field in form.hidden_fields %}
              {{ hidden_field.errors }}
              {{ hidden_field }}
          {% endfor %}

          <button type="submit" class="login__submit">Log in</button>
        </form>
      </div>
    {% endif %}

    {% if AUTHENTICATION_ENABLE_OIDC %}
      <div class="sso__container">
        <a href="{% url 'oidc_authentication_init' %}?next={{next}}" class="login__submit">Inloggen via Single Sign On</a>
      </div>
    {% endif %}
  </div>
{% endblock %}

homepage/templates/v3/login_failure.html
{% extends 'v3/_base.html' %}

{% block content %}
  <div class="login__container">
      <div class="credentials__container">
        Het inloggen is mislukt omdat je account (nog) niet geactiveerd is.<br />
        Vraag de beheerder om je account te activeren.
      </div>
      <div class="sso__container">
        <a href="{% url 'homepage:v3' '' %}" class="login__submit">Ga terug</a>
      </div>
  </div>
{% endblock %}

homepage/templates/v3/map.html
{% load django_vite %}
{% load static %}
<!DOCTYPE html>
<html lang="nl">
  <head>
    <title>Atlas · {{ config.ORGANIZATION_NAME }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" >

    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
    <link rel="shortcut icon" href="{% if config.FAVICON_URL %}{{ config.FAVICON_URL }}{% else %}{% static 'img/favicon.ico' %}{% endif %}" />

    {% vite_hmr_client %}
    {% vite_asset 'src/map.js' %}
</head>
  <body>
    <div id="app" class="app"></div>
    {{ data|json_script:"app-data" }}

    {% if google_maps %}
      <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ google_maps.api_key }}"></script>
    {% endif %}

    {% if street_smart %}
      <script type="text/javascript" src="https://unpkg.com/react@18.2.0/umd/react.production.min.js"></script>
      <script type="text/javascript" src="https://unpkg.com/react-dom@18.2.0/umd/react-dom.production.min.js"></script>
      <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@main/dist/en/v6.12.0/build/ol.js"></script>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"></script>
      <script type="text/javascript" src="https://streetsmart.cyclomedia.com/api/v23.7/StreetSmartApi.js"></script>
    {% endif %}
  </body>
</html>